import Link from 'next/link'
import { AppShell } from '@/components/app-shell'
import { createClient } from '@/lib/supabase/server'
import { Database, FileUp, Link2, Plus, ShieldCheck } from 'lucide-react'

export default async function DataSources() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return null
  const [{ count: lanes }, { count: contracts }, { count: shipments }, { count: carriers }] = await Promise.all([
    supabase.from('lanes').select('id', { count: 'exact', head: true }),
    supabase.from('contracts').select('id', { count: 'exact', head: true }),
    supabase.from('shipments').select('id', { count: 'exact', head: true }),
    supabase.from('carriers').select('id', { count: 'exact', head: true }),
  ])
  return <AppShell><main className="min-h-screen bg-[#f7f9fc] px-5 py-8 text-[#08111f] sm:px-8 sm:py-10"><div className="mx-auto max-w-[1480px]"><div className="flex flex-col gap-5 border-b border-[#dbe2ec] pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-extrabold uppercase tracking-[.18em] text-[#1769e0]">Data</p><h1 className="mt-2 text-3xl font-black tracking-[-.04em]">Data connections</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#66758a]">Bring the records your team already has. Start with an import today and move to automated connections when your systems support them.</p></div><Link href="/import" className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#1769e0] px-4 text-xs font-bold text-white"><FileUp size={15}/> Add existing data</Link></div>
<section className="mt-7 grid gap-4 md:grid-cols-3"><article className="rounded-2xl border border-[#dbe2ec] bg-white p-5"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#edf4ff] text-[#1769e0]"><Link2 size={17}/></div><h2 className="mt-5 text-sm font-extrabold">Connect a system</h2><p className="mt-2 text-xs leading-5 text-[#66758a]">Use an approved API or connector when your TMS, ERP or data platform supports one.</p><button disabled className="mt-5 w-full rounded-xl border border-[#dbe2ec] px-3 py-2.5 text-xs font-bold text-[#9aa4b1]">Connectors coming next</button></article><article className="rounded-2xl border border-[#dbe2ec] bg-white p-5"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#edf4ff] text-[#1769e0]"><FileUp size={17}/></div><h2 className="mt-5 text-sm font-extrabold">Use existing records</h2><p className="mt-2 text-xs leading-5 text-[#66758a]">Import CSV, Excel, JSON, TSV and other supported operational exports. GhostLane maps them before saving.</p><Link href="/import" className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#08111f] px-3 py-2.5 text-xs font-bold text-white">Import records</Link></article><article className="rounded-2xl border border-[#dbe2ec] bg-white p-5"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#edf4ff] text-[#1769e0]"><Plus size={17}/></div><h2 className="mt-5 text-sm font-extrabold">Start from your operation</h2><p className="mt-2 text-xs leading-5 text-[#66758a]">If there is no structured history, begin recording lanes, contracts and shipments and build the baseline over time.</p><Link href="/contracts" className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl border border-[#cbd6e5] px-3 py-2.5 text-xs font-bold text-[#526174]">Open workspace</Link></article></section>
<section className="mt-5 rounded-2xl border border-[#dbe2ec] bg-white"><div className="flex items-center justify-between border-b border-[#edf0f5] p-5"><div><div className="flex items-center gap-2 text-xs font-bold"><Database size={15} className="text-[#1769e0]"/> Current workspace data</div><p className="mt-1 text-xs text-[#8490a0]">Counts are read from your authenticated organization.</p></div><div className="flex items-center gap-2 text-[11px] font-bold text-[#4d7a61]"><ShieldCheck size={14}/> Organization scoped</div></div><div className="grid grid-cols-2 md:grid-cols-4">{[['Lanes',lanes],['Contracts',contracts],['Shipments',shipments],['Carriers',carriers]].map(([name,count])=><div key={String(name)} className="border-b border-[#edf0f5] p-5 last:border-0 md:border-b-0 md:border-r md:last:border-0"><div className="text-[10px] font-bold uppercase tracking-[.12em] text-[#8490a0]">{String(name)}</div><div className="mt-2 text-2xl font-black">{Number(count ?? 0).toLocaleString()}</div></div>)}</div></section></div></main></AppShell>
}
