'use client'
import Link from 'next/link'
import { usePathname, useRouter } from 'next/navigation'
import { useEffect, useState, type ComponentType } from 'react'
import { BarChart3, Bell, BriefcaseBusiness, ChevronDown, CircleDollarSign, Command, FileText, LayoutDashboard, Map, Menu, PackageSearch, Search, Settings, Truck, X, Database, BrainCircuit, Bot } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'

type Icon=ComponentType<{size?:number;className?:string}>
type Child={label:string;href:string;icon:Icon}
type Group={label:string;icon:Icon;children:Child[]}
type Item={label:string;href:string;icon:Icon}
const groups:Group[]=[
 {label:'Intelligence',icon:BrainCircuit,children:[{label:'Lane Intelligence',href:'/?view=lanes',icon:Map},{label:'Forecasts',href:'/?view=forecasts',icon:BarChart3},{label:'Ghost Risk',href:'/?view=risk',icon:CircleDollarSign}]},
 {label:'Procurement',icon:BriefcaseBusiness,children:[{label:'Recommendations',href:'/?view=recommendations',icon:BrainCircuit},{label:'RFQs',href:'/?view=rfqs',icon:FileText},{label:'Carriers',href:'/?view=carriers',icon:Truck},{label:'Contracts',href:'/?view=contracts',icon:FileText}]},
 {label:'Shipments',icon:PackageSearch,children:[{label:'All Shipments',href:'/?view=shipments',icon:PackageSearch},{label:'Exceptions',href:'/?view=exceptions',icon:CircleDollarSign}]},
 {label:'Finance',icon:CircleDollarSign,children:[{label:'Freight Spend',href:'/?view=spend',icon:CircleDollarSign},{label:'Ghost Cost',href:'/?view=ghost-cost',icon:CircleDollarSign},{label:'Savings',href:'/?view=savings',icon:BarChart3}]},
]
const direct:Item[]=[{label:'Ask GhostLane',href:'/?view=copilot',icon:Bot},{label:'Reports',href:'/?view=reports',icon:FileText}]
const pageNames:Record<string,string>={'/':'Overview','/import':'Data ingestion','/settings':'Settings'}
const viewNames:Record<string,string>={lanes:'Lane Intelligence',forecasts:'Forecasts',risk:'Ghost Risk',recommendations:'Recommendations',rfqs:'RFQs',carriers:'Carrier intelligence',contracts:'Contracts',shipments:'Shipment execution',exceptions:'Exceptions',spend:'Freight spend','ghost-cost':'Ghost cost',savings:'Savings',copilot:'Ask GhostLane',reports:'Reports'}

export function AppShell({children}:{children:React.ReactNode}){
 const pathname=usePathname();const router=useRouter();const[open,setOpen]=useState(false);const[expanded,setExpanded]=useState<string[]>(groups.map(g=>g.label));const[profileOpen,setProfileOpen]=useState(false);const[searchOpen,setSearchOpen]=useState(false);const[loggingOut,setLoggingOut]=useState(false)
 const view=typeof window!=='undefined'?new URLSearchParams(window.location.search).get('view'):null;const page=view?(viewNames[view]||'Workspace'):(pageNames[pathname]||'Overview')
 useEffect(()=>{setOpen(false);setProfileOpen(false)},[pathname])
 useEffect(()=>{const f=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);setProfileOpen(false);setSearchOpen(false)}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearchOpen(true)}};addEventListener('keydown',f);return()=>removeEventListener('keydown',f)},[])
 const logout=async()=>{if(loggingOut)return;setLoggingOut(true);await createClient().auth.signOut();router.replace('/login');router.refresh()}
 const jump=(href:string)=>{router.push(href);setSearchOpen(false)}
 const linkClass=(active:boolean)=>`flex items-center gap-3 rounded-xl px-3 py-2.5 text-[12px] font-bold ${active?'bg-[#edf4ff] text-[#1769e0]':'text-[#59687b] hover:bg-[#f6f8fb] hover:text-[#08111f]'}`
 return <div className="min-h-screen bg-[#f6f8fb] text-[#08111f]">
  {open&&<button aria-label="Close navigation" onClick={()=>setOpen(false)} className="fixed inset-0 z-50 bg-[#08111f]/15 lg:hidden"/>
  }<aside className={`fixed inset-y-0 left-0 z-[70] flex w-[272px] flex-col border-r border-[#dbe2ec] bg-white shadow-[16px_0_50px_rgba(8,17,31,.07)] transition-transform duration-200 lg:translate-x-0 ${open?'translate-x-0':'-translate-x-full'}`}>
   <div className="flex h-[64px] items-center border-b border-[#edf0f5] px-4"><button onClick={()=>setOpen(false)} className="mr-3 flex h-8 w-8 items-center justify-center rounded-lg border border-[#dbe2ec] lg:hidden"><X size={16}/></button><Link href="/" className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#1769e0] text-sm font-black text-white">G</span><span><span className="block text-[16px] font-black tracking-[-.04em]">GhostLane</span><span className="block text-[7px] font-extrabold uppercase tracking-[.16em] text-[#8a96a6]">Freight intelligence</span></span></Link></div>
   <div className="border-b border-[#edf0f5] p-3"><div className="rounded-xl border border-[#e2e7ee] bg-[#fafbfd] p-3"><div className="text-[10px] font-extrabold">GhostLane workspace</div><div className="mt-1 flex items-center gap-1.5 text-[9px] text-[#7f8b9b]"><span className="h-1.5 w-1.5 rounded-full bg-[#22a06b]"/>Operational data connected</div></div></div>
   <nav className="flex-1 overflow-y-auto px-3 py-4"><div className="mb-2 px-3 text-[9px] font-black uppercase tracking-[.18em] text-[#a0a9b5]">Command center</div><Link href="/" className={linkClass(!view&&pathname==='/')}><LayoutDashboard size={16}/>Overview</Link>
    {groups.map(group=>{const Icon=group.icon;const isOpen=expanded.includes(group.label);return <div key={group.label} className="mt-1"><button onClick={()=>setExpanded(x=>x.includes(group.label)?x.filter(v=>v!==group.label):[...x,group.label])} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-[12px] font-bold text-[#59687b] hover:bg-[#f6f8fb]"><Icon size={16}/><span className="flex-1 text-left">{group.label}</span><ChevronDown size={13} className={`transition-transform ${isOpen?'rotate-180':''}`}/></button>{isOpen&&<div className="ml-3 border-l border-[#e4e9ef] pl-2">{group.children.map(child=>{const C=child.icon;const active=view===child.href.split('=')[1];return <Link key={child.href} href={child.href} className={linkClass(active)}><C size={14}/>{child.label}</Link>})}</div>}</div>})}
    <div className="my-4 border-t border-[#edf0f5]"/>{direct.map(item=>{const Icon=item.icon;return <Link key={item.href} href={item.href} className={linkClass(view===item.href.split('=')[1])}><Icon size={16}/>{item.label}</Link>})}<div className="my-4 border-t border-[#edf0f5]"/><div className="mb-2 px-3 text-[9px] font-black uppercase tracking-[.18em] text-[#a0a9b5]">Administration</div><Link href="/settings" className={linkClass(pathname.startsWith('/settings'))}><Settings size={16}/>Settings</Link><Link href="/import" className={linkClass(pathname==='/import')}><Database size={16}/>Data sources</Link>
   </nav><div className="border-t border-[#edf0f5] p-3"><div className="rounded-xl bg-[#f7f9fc] p-3"><div className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#22a06b]"/><span className="text-[10px] font-extrabold">Workspace healthy</span></div><div className="mt-1 text-[9px] text-[#8994a3]">Predictions use connected records</div></div></div>
  </aside>
  <div className="min-h-screen lg:pl-[272px]"><header className="sticky top-0 z-40 h-[64px] border-b border-[#dbe2ec] bg-white/95 backdrop-blur"><div className="flex h-full items-center px-4 sm:px-6"><button onClick={()=>setOpen(v=>!v)} className="flex h-9 w-9 items-center justify-center rounded-lg border border-[#dbe2ec] lg:hidden"><Menu size={17}/></button><div className="ml-3 flex items-center gap-2 text-[12px] font-extrabold"><span className="text-[#9aa4b1]">Operations</span><span className="text-[#c7ced7]">/</span><span>{page}</span></div><div className="mx-6 hidden max-w-[480px] flex-1 lg:block"><button onClick={()=>setSearchOpen(true)} className="flex h-9 w-full items-center gap-2.5 rounded-lg border border-[#e1e6ed] bg-[#f8fafc] px-3 text-left hover:bg-white"><Search size={14} className="text-[#8793a2]"/><span className="flex-1 text-[11px] text-[#8994a3]">Search lanes, shipments, carriers, contracts…</span><span className="flex items-center gap-0.5 rounded border border-[#dce2e9] bg-white px-1.5 py-0.5 text-[9px] font-bold"><Command size={9}/>K</span></button></div><div className="ml-auto flex items-center gap-2"><div className="hidden items-center gap-2 rounded-full border border-[#dfeee6] bg-[#f5fbf7] px-2.5 py-1.5 md:flex"><span className="h-1.5 w-1.5 rounded-full bg-[#22a06b]"/><span className="text-[9px] font-extrabold text-[#39765a]">Data connected</span></div><button onClick={()=>setSearchOpen(true)} className="flex h-9 w-9 items-center justify-center rounded-lg lg:hidden"><Search size={16}/></button><button className="relative flex h-9 w-9 items-center justify-center rounded-lg"><Bell size={16}/><span className="absolute right-[9px] top-[8px] h-1.5 w-1.5 rounded-full bg-[#1769e0] ring-2 ring-white"/></button><div className="relative border-l border-[#e5e9ef] pl-2"><button onClick={()=>setProfileOpen(v=>!v)} className="flex items-center gap-2 rounded-lg p-1 hover:bg-[#f5f7fa]"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#08111f] text-[10px] font-black text-white">U</span><ChevronDown size={12}/></button>{profileOpen&&<div className="absolute right-0 top-11 w-48 rounded-xl border border-[#dbe2ec] bg-white p-1.5 shadow-xl"><Link href="/settings" className="block rounded-lg px-3 py-2 text-[11px] font-bold hover:bg-[#f5f7fa]">Settings</Link><button onClick={logout} disabled={loggingOut} className="w-full rounded-lg px-3 py-2 text-left text-[11px] font-bold hover:bg-[#f5f7fa]">{loggingOut?'Signing out…':'Sign out'}</button></div>}</div></div></div></header>
   {searchOpen&&<div className="fixed inset-0 z-[100] bg-[#08111f]/20 p-4 pt-20" onClick={()=>setSearchOpen(false)}><div className="mx-auto max-w-2xl overflow-hidden rounded-2xl border border-[#dbe2ec] bg-white shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center gap-3 border-b border-[#edf0f5] px-4 py-3"><Search size={17} className="text-[#8994a3]"/><input autoFocus onKeyDown={e=>{if(e.key==='Enter'&&e.currentTarget.value.trim())jump(`/?view=lanes&search=${encodeURIComponent(e.currentTarget.value.trim())}`)}} placeholder="Search or jump to a module…" className="flex-1 bg-transparent text-sm outline-none"/><button onClick={()=>setSearchOpen(false)} className="text-[10px] font-bold text-[#8994a3]">ESC</button></div><div className="grid gap-1 p-3 sm:grid-cols-2"><button onClick={()=>jump('/?view=lanes')} className="rounded-xl p-3 text-left hover:bg-[#f6f8fb]"><div className="text-xs font-extrabold">Lane Intelligence</div><div className="mt-1 text-[10px] text-[#8994a3]">Search and rank lanes</div></button><button onClick={()=>jump('/?view=recommendations')} className="rounded-xl p-3 text-left hover:bg-[#f6f8fb]"><div className="text-xs font-extrabold">Recommendations</div><div className="mt-1 text-[10px] text-[#8994a3]">Review procurement actions</div></button><button onClick={()=>jump('/?view=shipments')} className="rounded-xl p-3 text-left hover:bg-[#f6f8fb]"><div className="text-xs font-extrabold">Shipments</div><div className="mt-1 text-[10px] text-[#8994a3]">Open execution records</div></button><button onClick={()=>jump('/?view=copilot')} className="rounded-xl p-3 text-left hover:bg-[#f6f8fb]"><div className="text-xs font-extrabold">Ask GhostLane</div><div className="mt-1 text-[10px] text-[#8994a3]">Investigate your network</div></button></div></div></div>}
   {children}</div></div>
}
