'use client'
import Link from 'next/link'
import { usePathname, useRouter } from 'next/navigation'
import { useEffect, useState } from 'react'
import { BarChart3, CircleAlert, FileText, LayoutDashboard, Map, Menu, PackageSearch, Settings, Truck, X, Database, ClipboardList, ClipboardCheck, Search, Bell, ChevronDown, LogOut, Command } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'

const nav=[['Overview','/',LayoutDashboard],['Contract Intelligence','/contract-intelligence',ClipboardCheck],['Lanes','/lanes',Map],['Contracts','/contracts',FileText],['Shipments','/shipments',PackageSearch],['Carriers','/carriers',Truck],['Risk Analysis','/risk',CircleAlert],['Scenarios','/scenarios',BarChart3],['Reports','/reports',ClipboardList],['Data Sources','/data-sources',Database]] as const

const pageNames:Record<string,string>={'/':'Overview','/contract-intelligence':'Contract Intelligence','/lanes':'Lanes','/contracts':'Contracts','/shipments':'Shipments','/carriers':'Carriers','/risk':'Risk Analysis','/scenarios':'Scenarios','/reports':'Reports','/data-sources':'Data Sources','/settings':'Settings'}

export function AppShell({children}:{children:React.ReactNode}){
  const pathname=usePathname(); const router=useRouter(); const[open,setOpen]=useState(false); const[profileOpen,setProfileOpen]=useState(false); const[loggingOut,setLoggingOut]=useState(false); const[searchOpen,setSearchOpen]=useState(false)
  const page=pageNames[pathname] ?? Object.entries(pageNames).find(([p])=>p!=='/'&&pathname.startsWith(p))?.[1] ?? 'Overview'
  useEffect(()=>{setOpen(false);setProfileOpen(false)},[pathname])
  useEffect(()=>{const f=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);setProfileOpen(false);setSearchOpen(false)};if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearchOpen(true)}};addEventListener('keydown',f);return()=>removeEventListener('keydown',f)},[])
  const handleLogout=async()=>{if(loggingOut)return;setLoggingOut(true);await createClient().auth.signOut();router.replace('/login');router.refresh()}
  return <div className="min-h-screen bg-[#f6f8fb] text-[#08111f]">
    <button aria-label="Toggle navigation" onClick={()=>setOpen(v=>!v)} className="fixed left-5 top-5 z-[80] flex h-10 w-10 items-center justify-center rounded-xl border border-[#d5dfeb] bg-white shadow-sm lg:left-6">{open?<X size={19}/>:<Menu size={19}/>}</button>
    {open&&<button aria-label="Close navigation" onClick={()=>setOpen(false)} className="fixed inset-0 z-50 bg-[#08111f]/10 lg:bg-transparent"/>}
    <aside className={`fixed inset-y-0 left-0 z-[70] flex w-[272px] flex-col border-r border-[#dbe2ec] bg-white shadow-[16px_0_50px_rgba(8,17,31,.07)] transition-transform duration-200 ${open?'translate-x-0':'-translate-x-full'}`}>
      <div className="flex h-[72px] items-center border-b border-[#edf0f5] pl-[72px] pr-5"><Link href="/" className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#1769e0] text-sm font-black text-white">G</span><span><span className="block text-[17px] font-black tracking-[-.04em]">GhostLane</span><span className="block text-[8px] font-extrabold uppercase tracking-[.15em] text-[#8a96a6]">Freight intelligence</span></span></Link></div>
      <div className="border-b border-[#edf0f5] p-3"><button className="flex w-full items-center gap-3 rounded-xl border border-[#e2e7ee] bg-[#fafbfd] p-2.5 text-left"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#edf4ff] text-[10px] font-black text-[#1769e0]">AC</div><div className="min-w-0 flex-1"><div className="truncate text-[11px] font-extrabold">Acme Logistics</div><div className="text-[9px] text-[#8a96a6]">Operations workspace</div></div><ChevronDown size={13} className="text-[#9aa4b1]"/></button></div>
      <nav className="flex-1 overflow-y-auto px-3 py-4"><div className="mb-2 px-3 text-[9px] font-black uppercase tracking-[.18em] text-[#a0a9b5]">Command center</div>{nav.map(([name,href,Icon])=>{const active=href==='/'?pathname==='/':pathname.startsWith(href);return <Link key={href} href={href} className={`group mb-0.5 flex items-center gap-3 rounded-xl px-3 py-2.5 text-[12px] font-bold transition ${active?'bg-[#edf4ff] text-[#1769e0]':'text-[#59687b] hover:bg-[#f6f8fb] hover:text-[#08111f]'}`}><Icon size={16} strokeWidth={1.9}/><span className="flex-1">{name}</span>{name==='Contract Intelligence'&&<span className="rounded-md bg-[#08111f] px-1.5 py-0.5 text-[8px] text-white">NEW</span>}</Link>})}<div className="my-4 border-t border-[#edf0f5]"/><div className="mb-2 px-3 text-[9px] font-black uppercase tracking-[.18em] text-[#a0a9b5]">Administration</div><Link href="/settings" className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-[12px] font-bold ${pathname.startsWith('/settings')?'bg-[#edf4ff] text-[#1769e0]':'text-[#59687b] hover:bg-[#f6f8fb]'}`}><Settings size={16}/><span>Settings</span></Link></nav>
      <div className="border-t border-[#edf0f5] p-3"><div className="rounded-xl bg-[#f7f9fc] p-3"><div className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#22a06b]"/><span className="text-[10px] font-extrabold">Workspace healthy</span></div><div className="mt-1 text-[9px] text-[#8994a3]">Data access is protected</div></div></div>
    </aside>
    <div className="min-h-screen">
      <header className="sticky top-0 z-40 h-[64px] border-b border-[#dfe5ed] bg-white/95 backdrop-blur-sm">
        <div className="flex h-full items-center gap-4 pl-[76px] pr-5 lg:pl-[82px]">
          <div className="flex min-w-[190px] items-center gap-3"><div className="text-[10px] font-bold uppercase tracking-[.14em] text-[#9aa4b1]">Workspace</div><div className="h-4 w-px bg-[#dbe2ec]"/><div className="text-[13px] font-extrabold text-[#08111f]">{page}</div></div>
          <div className="mx-auto hidden max-w-[520px] flex-1 md:block"><button onClick={()=>setSearchOpen(true)} className="flex h-10 w-full items-center gap-3 rounded-xl border border-[#dbe2ec] bg-[#f8fafc] px-3 text-left text-[12px] text-[#8a96a6] transition hover:border-[#cbd5e1] hover:bg-white"><Search size={15}/><span className="flex-1">Search lanes, carriers, contracts…</span><kbd className="rounded-md border border-[#dbe2ec] bg-white px-1.5 py-0.5 text-[9px] font-bold text-[#8a96a6]">⌘ K</kbd></button></div>
          <div className="ml-auto flex items-center gap-1.5">
            <div className="hidden items-center gap-2 px-2 lg:flex"><span className="h-1.5 w-1.5 rounded-full bg-[#22a06b]"/><span className="text-[10px] font-bold text-[#667487]">Data connected</span></div>
            <button aria-label="Notifications" className="relative flex h-9 w-9 items-center justify-center rounded-lg text-[#667487] transition hover:bg-[#f3f6fa] hover:text-[#08111f]"><Bell size={17}/><span className="absolute right-[9px] top-[8px] h-1.5 w-1.5 rounded-full bg-[#1769e0] ring-2 ring-white"/></button>
            <div className="relative ml-1 border-l border-[#e3e8ef] pl-3"><button onClick={()=>setProfileOpen(v=>!v)} className="flex items-center gap-2 rounded-xl px-1.5 py-1 transition hover:bg-[#f5f7fa]"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#1769e0] text-[10px] font-black text-white">AC</span><span className="hidden text-left lg:block"><span className="block text-[11px] font-extrabold leading-4">Account</span><span className="block text-[9px] text-[#8994a3]">Workspace user</span></span><ChevronDown size={13} className={`text-[#8994a3] transition-transform ${profileOpen?'rotate-180':''}`}/></button>{profileOpen&&<div className="absolute right-0 top-12 w-52 overflow-hidden rounded-xl border border-[#dbe2ec] bg-white p-1.5 shadow-[0_16px_40px_rgba(8,17,31,.12)]"><Link href="/settings" className="flex items-center gap-2 rounded-lg px-3 py-2.5 text-[11px] font-bold text-[#59687b] hover:bg-[#f5f7fa] hover:text-[#08111f]"><Settings size={15}/>Settings</Link><button type="button" onClick={handleLogout} disabled={loggingOut} className="flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-[11px] font-bold text-[#59687b] hover:bg-[#f5f7fa] hover:text-[#08111f] disabled:opacity-50"><LogOut size={15}/>{loggingOut?'Signing out…':'Sign out'}</button></div>}</div>
          </div>
        </div>
      </header>
      {searchOpen&&<div className="fixed inset-0 z-[100] bg-[#08111f]/20 p-4 pt-20" onClick={()=>setSearchOpen(false)}><div className="mx-auto max-w-2xl overflow-hidden rounded-2xl border border-[#dbe2ec] bg-white shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center gap-3 border-b border-[#edf0f5] px-4 py-3"><Search size={17} className="text-[#8994a3]"/><input autoFocus placeholder="Search lanes, carriers, contracts…" className="flex-1 bg-transparent text-sm outline-none placeholder:text-[#a0a9b5]"/><button onClick={()=>setSearchOpen(false)} className="text-[10px] font-bold text-[#8994a3]">ESC</button></div><div className="p-5 text-[11px] text-[#8994a3]">Search across your connected GhostLane workspace.</div></div></div>}
      {children}
    </div>
  </div>
}
