import Link from 'next/link'
import { ArrowUpRight, Database, FileUp } from 'lucide-react'
import { AppShell } from '@/components/app-shell'
import { createClient } from '@/lib/supabase/server'

type Resource = 'lanes' | 'contracts' | 'shipments' | 'carriers'
const configs: Record<Resource, { select: string; render: (row: Record<string, unknown>) => string[] }> = {
  lanes: { select: 'id, origin, destination, mode, contracted_volume, materialized_volume, risk_score', render: r => [String(r.origin ?? '') + ' → ' + String(r.destination ?? ''), String(r.mode ?? ''), String(r.contracted_volume ?? 0), String(r.materialized_volume ?? 0), `${Number(r.contracted_volume) ? ((Number(r.materialized_volume) / Number(r.contracted_volume)) * 100).toFixed(1) : '0.0'}%`, Number(r.risk_score ?? 0).toFixed(0)] },
  contracts: { select: 'id, contract_id, lane_id, carrier, contracted_volume, contract_rate, start_date, end_date', render: r => [String(r.contract_id ?? ''), String(r.lane_id ?? '').slice(0, 8), String(r.carrier ?? ''), String(r.contracted_volume ?? 0), String(r.contract_rate ?? 0), String(r.start_date ?? ''), String(r.end_date ?? '')] },
  shipments: { select: 'id, shipment_id, lane_id, carrier, shipment_date, volume, status', render: r => [String(r.shipment_id ?? ''), String(r.lane_id ?? '').slice(0, 8), String(r.carrier ?? ''), String(r.shipment_date ?? ''), String(r.volume ?? 0), String(r.status ?? '')] },
  carriers: { select: 'id, name, acceptance_rate, rejection_rate, cancellation_rate, realization_rate', render: r => [String(r.name ?? ''), String(r.acceptance_rate ?? 0), String(r.rejection_rate ?? 0), String(r.cancellation_rate ?? 0), String(r.realization_rate ?? 0)] },
}

export async function DataPage({ title, description, action='Import data', columns, resource }: { title:string; description:string; action?:string; columns:string[]; resource?:Resource }) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!resource || !user) {
    return <AppShell><main className="min-h-screen bg-[#f7f9fc] px-5 py-8 text-[#08111f] sm:px-8 sm:py-10"><div className="mx-auto max-w-[1480px]"><div className="border-b border-[#dbe2ec] pb-7"><p className="text-[11px] font-extrabold uppercase tracking-[.18em] text-[#1769e0]">Workspace</p><h1 className="mt-2 text-3xl font-black tracking-[-.04em]">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#66758a]">{description}</p></div><section className="mt-7 rounded-2xl border border-[#dbe2ec] bg-white px-5 py-20 text-center"><Database className="mx-auto text-[#1769e0]" size={20}/><h2 className="mt-4 text-sm font-extrabold">{user ? 'Module not yet configured' : 'Sign in required'}</h2></section></div></main></AppShell>
  }
  const config = configs[resource]
  const { data, error } = await supabase.from(resource).select(config.select).order('created_at', { ascending: false }).limit(100)
  if (error) console.error('GhostLane data query failed:', error.message)
  const rows = Array.isArray(data) ? (data as unknown as Record<string, unknown>[]) : []
  return <AppShell><main className="min-h-screen bg-[#f7f9fc] px-5 py-8 text-[#08111f] sm:px-8 sm:py-10"><div className="mx-auto max-w-[1480px]"><div className="flex flex-col gap-4 border-b border-[#dbe2ec] pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-extrabold uppercase tracking-[.18em] text-[#1769e0]">Workspace</p><h1 className="mt-2 text-3xl font-black tracking-[-.04em]">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#66758a]">{description}</p></div><Link href="/import" className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-[#1769e0] px-4 text-xs font-bold text-white hover:bg-[#0f57bd]"><FileUp size={15}/>{action}</Link></div><section className="mt-7 rounded-2xl border border-[#dbe2ec] bg-white"><div className="flex items-center justify-between border-b border-[#edf0f5] p-5"><div className="flex items-center gap-2 text-xs font-bold text-[#526174]"><Database size={15}/> Connected workspace data</div><div className="text-[11px] text-[#8a96a6]">{rows.length} record{rows.length === 1 ? '' : 's'}</div></div>{rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="bg-[#fafbfd] text-[10px] uppercase tracking-[.12em] text-[#8490a0]"><tr>{columns.map(c=><th key={c} className="px-5 py-3 font-bold">{c}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={String(row.id)} className="border-t border-[#edf0f5]">{config.render(row).map((cell,i)=><td key={i} className="px-5 py-3 font-medium">{cell}</td>)}</tr>)}</tbody></table></div> : <div className="px-5 py-20 text-center"><Database className="mx-auto text-[#1769e0]" size={19}/><h2 className="mt-4 text-sm font-extrabold">No data connected</h2><p className="mx-auto mt-1 max-w-md text-xs leading-5 text-[#7c8797]">This view reads only from your authenticated workspace. Import operational records to populate it.</p><Link href="/import" className="mt-5 inline-flex items-center gap-1 text-xs font-bold text-[#1769e0]">Connect data <ArrowUpRight size={13}/></Link></div>}</section></div></main></AppShell>
}