'use client'

import { useMemo, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, ExternalLink, MapPinned, Navigation, PackageCheck, ShieldAlert, Truck } from 'lucide-react'

type Shipment = { shipment_id:string; lane_id:string; carrier:string; shipment_date:string; volume:number; status:string }
type Lane = { id:string; origin:string; destination:string; mode:string; carrier:string|null; distance_km:number|null; risk_score:number|null }

const num=(n:number)=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:0}).format(Math.max(0,n))
const pct=(n:number)=>`${Math.round(Math.max(0,Math.min(100,n)))}%`
const eta=(distance:number|null, mode:string)=>{const km=Math.max(0,Number(distance||0)); const speed=mode.toLowerCase().includes('road')?48:mode.toLowerCase().includes('rail')?55:35; return km?`${Math.max(1,Math.round(km/speed))}h estimated`: 'ETA unavailable'}

export function DriverNavigation({ shipments, lanes }:{ shipments:Shipment[]; lanes:Lane[] }) {
  const [shipmentId,setShipmentId]=useState(shipments[0]?.shipment_id||'')
  const shipment=shipments.find(s=>s.shipment_id===shipmentId)||shipments[0]
  const lane=lanes.find(l=>l.id===shipment?.lane_id)
  const mapUrl=useMemo(()=>lane?`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(lane.origin)}&destination=${encodeURIComponent(lane.destination)}`:'',[lane])
  if(!shipment||!lane) return <main className="min-h-[calc(100vh-64px)] bg-[#f6f8fb] px-5 py-10 text-[#08111f]"><div className="mx-auto max-w-xl rounded-3xl border border-[#dbe2ec] bg-white p-10 text-center"><MapPinned className="mx-auto text-[#1769e0]" size={30}/><h1 className="mt-4 text-xl font-black">Navigation needs shipment + lane records</h1><p className="mt-2 text-xs leading-5 text-[#66758a]">Import actual shipment and lane data first. GhostLane will not invent a route when the source records are missing.</p><Link href="/import" className="mt-6 inline-flex rounded-xl bg-[#1769e0] px-4 py-2.5 text-xs font-bold text-white">Import data</Link></div></main>
  const risk=Number(lane.risk_score||0)
  return <main className="min-h-[calc(100vh-64px)] bg-[#f6f8fb] px-4 py-7 text-[#08111f] sm:px-6 lg:px-8"><div className="mx-auto max-w-[1480px]">
    <div className="flex flex-col gap-4 border-b border-[#dbe2ec] pb-6 sm:flex-row sm:items-end sm:justify-between"><div><Link href="/" className="inline-flex items-center gap-2 text-[10px] font-black text-[#1769e0]"><ArrowLeft size={13}/>Command center</Link><div className="mt-4 text-[9px] font-black uppercase tracking-[.18em] text-[#1769e0]">Shipment execution</div><h1 className="mt-2 text-3xl font-black tracking-[-.05em]">Driver navigation</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#66758a]">Turn an approved shipment into a navigation handoff. Routing is delegated to the map provider; GhostLane supplies the operational context and risk signal.</p></div><a href={mapUrl} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#1769e0] px-4 py-3 text-[11px] font-black text-white"><Navigation size={15}/>Open directions<ExternalLink size={12}/></a></div>
    <section className="mt-6 grid gap-5 xl:grid-cols-[.72fr_1.28fr]">
      <aside className="rounded-3xl border border-[#dbe2ec] bg-white p-5"><div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.15em] text-[#8490a0]"><PackageCheck size={14}/> Shipment</div><select value={shipment.shipment_id} onChange={e=>setShipmentId(e.target.value)} className="mt-5 h-11 w-full rounded-xl border border-[#dbe2ec] bg-white px-3 text-xs font-bold outline-none focus:border-[#1769e0]">{shipments.map(s=><option key={s.shipment_id} value={s.shipment_id}>{s.shipment_id}</option>)}</select><div className="mt-5 space-y-3 text-xs"><div><span className="text-[#8994a3]">Carrier</span><div className="mt-1 font-extrabold">{shipment.carrier}</div></div><div><span className="text-[#8994a3]">Volume</span><div className="mt-1 font-extrabold">{num(Number(shipment.volume))}</div></div><div><span className="text-[#8994a3]">Status</span><div className="mt-1 font-extrabold">{shipment.status||'Recorded'}</div></div></div></aside>
      <section className="rounded-3xl border border-[#dbe2ec] bg-white p-6"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.15em] text-[#8490a0]"><Truck size={14}/> Route handoff</div><span className={`rounded-full px-2.5 py-1 text-[9px] font-black ${risk>=70?'bg-[#fff0f0] text-[#b54747]':risk>=45?'bg-[#fff8e7] text-[#9b6a00]':'bg-[#eef9f4] text-[#23825b]'}`}>{pct(risk)} ghost risk</span></div><div className="mt-7 flex items-center gap-4"><div className="min-w-0 flex-1"><div className="text-lg font-black">{lane.origin}</div><div className="mt-1 text-[10px] text-[#8994a3]">Origin</div></div><div className="h-px flex-1 bg-[#dbe2ec]"/><MapPinned size={20} className="text-[#1769e0]"/><div className="h-px flex-1 bg-[#dbe2ec]"/><div className="min-w-0 flex-1 text-right"><div className="text-lg font-black">{lane.destination}</div><div className="mt-1 text-[10px] text-[#8994a3]">Destination</div></div></div><div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-[#f7f9fc] p-4"><div className="text-[9px] font-black uppercase tracking-[.1em] text-[#8490a0]">Distance</div><div className="mt-2 text-xl font-black">{lane.distance_km?`${num(Number(lane.distance_km))} km`:'Unavailable'}</div></div><div className="rounded-2xl bg-[#f7f9fc] p-4"><div className="text-[9px] font-black uppercase tracking-[.1em] text-[#8490a0]">Planning ETA</div><div className="mt-2 text-xl font-black">{eta(lane.distance_km,lane.mode)}</div></div><div className="rounded-2xl bg-[#f7f9fc] p-4"><div className="text-[9px] font-black uppercase tracking-[.1em] text-[#8490a0]">Mode</div><div className="mt-2 text-xl font-black capitalize">{lane.mode}</div></div></div></section>
    </section>
    <section className="mt-5 rounded-3xl bg-[#08111f] p-6 text-white"><div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.15em] text-[#83b4ff]"><ShieldAlert size={14}/> Execution warning</div><h2 className="mt-4 text-xl font-black">{risk>=70?'Review before dispatch':risk>=45?'Dispatch with monitoring':'Ready for execution'}</h2><p className="mt-2 max-w-3xl text-xs leading-5 text-[#aab5c3]">{risk>=70?'This lane is high risk. Confirm the carrier and shipment commitment before dispatching.':risk>=45?'The lane is in the review band. Keep the shipment visible to the operations team during execution.':'No high-risk signal is present in the connected lane record.'}</p></section>
  </div></main>
}
