'use client'

import Link from 'next/link'
import { ArrowRight, BarChart3, ChevronRight, CircleAlert, Database, FileText, MapPin, ShieldCheck, Sparkles, Truck } from 'lucide-react'

type Feature = { icon: typeof FileText; label: string; title: string; copy: string }
const lanes: Array<[string, string, 'High' | 'Medium' | 'Low']> = [['Ludhiana → Nagpur','42%','High'],['Ahmedabad → Mumbai','24%','Medium'],['Bengaluru → Chennai','31%','Medium'],['Delhi → Mumbai','12%','Low']]
const features: Feature[] = [
  { icon: FileText, label: 'DETECT', title: 'Find ghost capacity', copy: 'Reconcile contract commitments with actual shipment movement and calculate lane-level realization.' },
  { icon: BarChart3, label: 'PREDICT', title: 'Score future risk', copy: 'Use historical lane and carrier behavior to identify routes likely to under-materialize.' },
  { icon: Truck, label: 'PRESCRIBE', title: 'Change the contract', copy: 'Turn the signal into a procurement action: flexible volume, tiered commitment, alternate carrier or spot exposure.' },
]

export function LandingPage() {
  return <main className="min-h-screen bg-[#f7f9fc] text-[#08111f]">
    <header className="sticky top-0 z-50 border-b border-[#dbe2ec] bg-white/90 backdrop-blur-xl"><div className="mx-auto flex h-[76px] max-w-[1440px] items-center justify-between px-5 sm:px-8"><Link href="/" className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#1769e0] text-sm font-black text-white">G</span><span><span className="block text-[17px] font-black tracking-[-.04em]">GhostLane</span><span className="block text-[8px] font-extrabold uppercase tracking-[.16em] text-[#8a96a6]">Freight intelligence</span></span></Link><nav className="hidden items-center gap-1 md:flex"><Link href="#product" className="rounded-lg px-4 py-2 text-xs font-bold text-[#647286]">Product</Link><Link href="#workflow" className="rounded-lg px-4 py-2 text-xs font-bold text-[#647286]">How it works</Link><Link href="#evidence" className="rounded-lg px-4 py-2 text-xs font-bold text-[#647286]">Evidence</Link></nav><div className="flex items-center gap-2"><Link href="/login" className="hidden rounded-xl px-3 py-2.5 text-xs font-bold text-[#526174] sm:inline-flex">Sign in</Link><Link href="/signup" className="inline-flex items-center gap-2 rounded-xl bg-[#1769e0] px-4 py-2.5 text-xs font-bold text-white">Build workspace <ArrowRight size={14}/></Link></div></div></header>

    <section className="overflow-hidden border-b border-[#dbe2ec] bg-white"><div className="mx-auto grid max-w-[1440px] gap-14 px-5 py-16 sm:px-8 lg:grid-cols-[.86fr_1.14fr] lg:items-center lg:py-24"><div><div className="inline-flex items-center gap-2 rounded-full border border-[#dbe2ec] bg-[#f8fafc] px-3 py-1.5 text-[10px] font-extrabold uppercase tracking-[.13em] text-[#607086]"><span className="h-1.5 w-1.5 rounded-full bg-[#1769e0]"/>Procurement intelligence for freight</div><h1 className="mt-6 max-w-2xl text-5xl font-black leading-[.94] tracking-[-.065em] sm:text-7xl">Know which capacity will actually move.</h1><p className="mt-6 max-w-xl text-base leading-7 text-[#627084] sm:text-lg">GhostLane connects contracts, shipments, lanes and carriers to expose unused capacity before it becomes another expensive contract decision.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/signup" className="inline-flex h-12 items-center gap-2 rounded-xl bg-[#1769e0] px-5 text-sm font-bold text-white">Start with your data <ArrowRight size={16}/></Link><Link href="#product" className="inline-flex h-12 items-center gap-2 rounded-xl border border-[#d0d9e5] bg-white px-5 text-sm font-bold text-[#526174]">Explore product <ChevronRight size={16}/></Link></div><div className="mt-8 flex flex-wrap gap-5 text-[10px] font-bold text-[#8490a0]"><span className="flex items-center gap-2"><ShieldCheck size={14} className="text-[#1769e0]"/>Organization isolated</span><span className="flex items-center gap-2"><Database size={14} className="text-[#1769e0]"/>Your operational data</span></div></div>

    <div className="relative"><div className="absolute -inset-10 bg-[#1769e0]/[.035] blur-3xl"/><div className="relative rounded-[28px] border border-[#cfd9e6] bg-[#eef3f8] p-2 shadow-[0_30px_90px_rgba(8,17,31,.12)] sm:p-3"><div className="overflow-hidden rounded-[22px] border border-[#dbe2ec] bg-white"><div className="flex h-12 items-center justify-between border-b border-[#edf0f5] px-4"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[#1769e0]"/><span className="text-[10px] font-extrabold">Network command center</span></div><span className="rounded-lg bg-[#f5f8fc] px-2 py-1 text-[8px] font-bold text-[#8490a0]">ILLUSTRATIVE PREVIEW</span></div><div className="grid grid-cols-3 gap-px bg-[#edf0f5]"><Metric label="CONTRACTED" value="4,820"/><Metric label="MATERIALIZED" value="3,491" note="72.4% realization"/><Metric label="GHOST CAPACITY" value="1,329" note="27.6% exposure" danger/></div><div className="grid gap-3 p-4 md:grid-cols-[1.08fr_.92fr]"><div className="rounded-2xl border border-[#e0e6ed] p-4"><div className="flex items-center justify-between"><div><div className="text-[9px] font-extrabold uppercase tracking-[.12em] text-[#1769e0]">Lane exposure</div><div className="mt-1 text-xs font-extrabold">Illustrative product view</div></div><MapPin size={15} className="text-[#8a96a6]"/></div><div className="mt-5 space-y-3">{lanes.map(([lane,pct,r])=><div key={lane}><div className="flex justify-between text-[9px] font-bold"><span>{lane}</span><span className={r==='High'?'text-[#b54747]':r==='Medium'?'text-[#a06a00]':'text-[#22a06b]'}>{pct} ghost</span></div><div className="mt-1.5 h-1.5 rounded-full bg-[#edf2f7]"><div className="h-full rounded-full bg-[#1769e0]" style={{width:pct}}/></div></div>)}</div></div><div className="rounded-2xl border border-[#e0e6ed] bg-[#fafbfd] p-4"><div className="flex items-center gap-2 text-[9px] font-extrabold uppercase tracking-[.12em] text-[#1769e0]"><Sparkles size={13}/>Decision signal</div><div className="mt-5 text-3xl font-black">62</div><div className="text-[9px] font-bold text-[#7e8a9a]">illustrative lanes needing review</div><div className="mt-5 rounded-xl border border-[#e2e7ee] bg-white p-3"><div className="text-[9px] font-bold text-[#8a96a6]">TOP ACTION</div><div className="mt-1 text-[11px] font-extrabold">Reduce committed volume</div><div className="mt-1 text-[9px] leading-4 text-[#7d8999]">Example signal only — workspace recommendations use connected data.</div></div></div></div></div></div></div></div></section>

    <section id="product" className="mx-auto max-w-[1440px] px-5 py-20 sm:px-8 sm:py-28"><div className="grid gap-10 lg:grid-cols-[.72fr_1.28fr] lg:items-end"><div><div className="text-[10px] font-extrabold uppercase tracking-[.18em] text-[#1769e0]">One operating picture</div><h2 className="mt-3 text-4xl font-black tracking-[-.055em] sm:text-5xl">Not another logistics dashboard.</h2></div><p className="max-w-2xl text-sm leading-6 text-[#66758a] sm:text-base">GhostLane is designed around the procurement decision: compare what was contracted with what materialized, understand the drivers, then decide what to contract next.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{features.map(({icon: Icon,label,title,copy})=><article key={label} className="rounded-3xl border border-[#dbe2ec] bg-white p-7 transition duration-200 hover:-translate-y-1 hover:shadow-[0_20px_55px_rgba(8,17,31,.07)]"><div className="flex items-center justify-between"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#edf4ff] text-[#1769e0]"><Icon size={19}/></span><span className="text-[9px] font-black tracking-[.18em] text-[#a0a9b5]">{label}</span></div><h3 className="mt-8 text-lg font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-[#66758a]">{copy}</p></article>)}</div></section>

    <section id="workflow" className="border-y border-[#dbe2ec] bg-[#08111f] text-white"><div className="mx-auto max-w-[1440px] px-5 py-20 sm:px-8 sm:py-24"><div className="max-w-2xl"><div className="text-[10px] font-extrabold uppercase tracking-[.18em] text-[#83b4ff]">Decision workflow</div><h2 className="mt-3 text-4xl font-black tracking-[-.055em] sm:text-5xl">From raw records to a procurement recommendation.</h2></div><div className="mt-12 grid gap-px overflow-hidden rounded-3xl border border-white/10 bg-white/10 md:grid-cols-5">{[['01','Contracts','Commitments, rates, lanes'],['02','Shipments','Actual movement, volume'],['03','Entity resolution','Match records to lanes'],['04','Risk engine','Realization + context'],['05','Recommendation','Contract with evidence']].map(([n,t,c])=><div key={n} className="bg-[#0d1828] p-6"><div className="text-[9px] font-black tracking-[.15em] text-[#83b4ff]">{n}</div><div className="mt-10 text-sm font-extrabold">{t}</div><div className="mt-2 text-[10px] leading-5 text-[#8f9cad]">{c}</div></div>)}</div></div></section>

    <section id="evidence" className="mx-auto max-w-[1440px] px-5 py-20 sm:px-8 sm:py-24"><div className="grid gap-10 lg:grid-cols-2"><div><div className="text-[10px] font-extrabold uppercase tracking-[.18em] text-[#1769e0]">Evidence layer</div><h2 className="mt-3 text-4xl font-black tracking-[-.055em]">Make capacity decisions from evidence, not intuition.</h2><p className="mt-5 max-w-xl text-sm leading-6 text-[#66758a]">GhostLane keeps the distinction between contracted capacity and materialized movement visible, so recommendations can be traced back to the underlying records.</p></div><div className="rounded-3xl border border-[#dbe2ec] bg-white p-7"><div className="flex items-start justify-between"><div><div className="text-[10px] font-extrabold uppercase tracking-[.15em] text-[#1769e0]">Evidence coverage</div><div className="mt-2 text-xl font-black">Every recommendation has a trail.</div></div><CircleAlert size={20} className="text-[#1769e0]"/></div><div className="mt-7 space-y-3">{['Historical realization by lane','Carrier acceptance and cancellation behavior','Contracted vs. materialized volume','Evidence coverage and data freshness'].map((x,i)=><div key={x} className="flex items-center gap-3 rounded-xl border border-[#edf0f5] px-4 py-3"><span className="flex h-6 w-6 items-center justify-center rounded-lg bg-[#edf4ff] text-[9px] font-black text-[#1769e0]">0{i+1}</span><span className="text-xs font-bold text-[#526174]">{x}</span></div>)}</div></div></div></section>

    <section className="border-t border-[#dbe2ec] bg-white"><div className="mx-auto flex max-w-[1440px] flex-col gap-6 px-5 py-12 sm:px-8 md:flex-row md:items-center md:justify-between"><div><div className="text-lg font-black">Build a procurement workspace around your real network.</div><div className="mt-1 text-xs text-[#7c8797]">Start with structured operational data. Add integrations as your deployment matures.</div></div><Link href="/signup" className="inline-flex h-11 items-center gap-2 rounded-xl bg-[#1769e0] px-5 text-xs font-bold text-white">Create workspace <ArrowRight size={15}/></Link></div></section><footer className="border-t border-[#dbe2ec] bg-white"><div className="mx-auto flex max-w-[1440px] justify-between px-5 py-7 text-[10px] font-semibold text-[#8994a3] sm:px-8"><span><b className="text-[#526174]">GhostLane</b> · Freight procurement intelligence</span><span className="hidden sm:inline">Prototype environment · India-first</span></div></footer>
  </main>
}

function Metric({ label, value, note, danger = false }: { label: string; value: string; note?: string; danger?: boolean }) {
  return <div className="bg-white p-4"><div className="text-[9px] font-bold text-[#8b96a5]">{label}</div><div className={`mt-2 text-2xl font-black ${danger ? 'text-[#b54747]' : ''}`}>{value}</div><div className={`mt-1 text-[9px] ${danger ? 'text-[#b54747]' : 'text-[#22a06b]'}`}>{note ?? 'capacity units'}</div></div>
}
