'use client'

import { useMemo, useState } from 'react'
import { ArrowLeft, BrainCircuit, CheckCircle2, ChevronRight, CircleAlert, FileText, Gauge, Route, Truck } from 'lucide-react'

type Lane = { id:string; origin:string; destination:string; mode:string; carrier:string|null; contracted_volume:number|null; materialized_volume:number|null; risk_score:number|null; distance_km:number|null }
type Shipment = { shipment_id:string; lane_id:string; carrier:string; shipment_date:string; volume:number; status:string }
type Contract = { contract_id:string; lane_id:string; carrier:string; contracted_volume:number; contract_rate:number; start_date:string; end_date:string }

type Props = { lane:Lane; shipments:Shipment[]; contracts:Contract[]; onBack:()=>void; onSim:()=>void }

const fmt=(n:number)=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:0}).format(n)
const pct=(n:number)=>`${Math.max(0,Math.min(100,n)).toFixed(0)}%`

export function Lane360Responsive({lane,shipments,contracts,onBack,onSim}:Props){
 const [tab,setTab]=useState('Overview')
 const c=Number(lane.contracted_volume||0), m=Number(lane.materialized_volume||0), utilization=c?m/c*100:0, risk=Number(lane.risk_score||0), ghost=Math.max(c-m,0)
 const laneShipments=useMemo(()=>shipments.filter(s=>s.lane_id===lane.id),[shipments,lane.id])
 const laneContracts=useMemo(()=>contracts.filter(x=>x.lane_id===lane.id),[contracts,lane.id])
 const tabs=['Overview','Forecast','Risk','Carriers','Rates','Contracts','Shipments']
 const content=()=>{
  if(tab==='Overview') return <div className="grid gap-4 md:grid-cols-2"><Panel title="Lane summary" icon={<Route size={17}/>}><Metric label="Origin" value={lane.origin}/><Metric label="Destination" value={lane.destination}/><Metric label="Mode" value={lane.mode||'—'}/><Metric label="Distance" value={lane.distance_km?`${fmt(Number(lane.distance_km))} km`:'—'}/></Panel><Panel title="Decision signal" icon={<BrainCircuit size={17}/>}><Signal label="Utilization" value={pct(utilization)}/><Signal label="Ghost exposure" value={fmt(ghost)}/><Signal label="Risk" value={pct(risk)}/><p className="mt-4 rounded-xl bg-[#f6f8fb] p-3 text-[11px] leading-5 text-[#66758a]">{risk>=70||utilization<65?'Consider a hybrid or lower commitment strategy.':'Current commitment is broadly aligned with realized movement.'}</p></Panel></div>
  if(tab==='Forecast') return <div className="grid gap-4 md:grid-cols-2"><Panel title="Movement baseline" icon={<Gauge size={17}/>}><div className="text-3xl font-black">{fmt(m)}</div><p className="mt-1 text-[10px] text-[#8994a3]">Realized units on this lane</p><div className="mt-6 flex h-32 items-end gap-2">{[.55,.68,.48,.74,.62,.81,.72,.9].map((v,i)=><div key={i} className="flex-1 rounded-t-md bg-[#1769e0]/20" style={{height:`${v*100}%`}}/></div></Panel><Panel title="Forecast interpretation"><p className="text-xs leading-6 text-[#526174]">The forecast view uses the movement baseline available for this lane. More shipment history increases evidence quality; GhostLane avoids presenting unsupported precision.</p><div className="mt-5 rounded-xl border border-[#dbe2ec] p-4"><div className="text-[9px] font-black uppercase tracking-wide text-[#8994a3]">Planning range</div><div className="mt-2 text-sm font-extrabold">{fmt(Math.round(m*.9))} – {fmt(Math.round(m*1.1))} units</div></div></Panel></div>
  if(tab==='Risk') return <div className="grid gap-4 md:grid-cols-2"><Panel title="Ghost risk" icon={<CircleAlert size={17}/>}><div className="text-5xl font-black">{pct(risk)}</div><div className="mt-4 h-2 rounded-full bg-[#edf0f5]"><div className="h-full rounded-full bg-[#1769e0]" style={{width:`${risk}%`}}/></div><div className="mt-3 text-xs font-bold">{risk>=70?'High':risk>=45?'Medium':'Low'} risk</div></Panel><Panel title="Risk drivers"><div className="space-y-3"><Driver title="Utilization gap" value={pct(utilization)} detail={`${fmt(ghost)} unrealized units`}/><Driver title="Shipment evidence" value={String(laneShipments.length)} detail="linked shipment records"/><Driver title="Contract evidence" value={String(laneContracts.length)} detail="linked contract records"/></div></Panel></div>
  if(tab==='Carriers') return <Panel title="Lane carriers" icon={<Truck size={17}/>}><div className="rounded-xl border border-[#dbe2ec] p-4"><div className="text-sm font-extrabold">{lane.carrier||'Carrier not assigned'}</div><div className="mt-1 text-[10px] text-[#8994a3]">Primary carrier recorded for this lane</div></div>{laneShipments.length>0&&<div className="mt-3 text-[10px] text-[#8994a3]">{new Set(laneShipments.map(s=>s.carrier).filter(Boolean)).size} carrier name(s) appear in shipment history.</div>}</Panel>
  if(tab==='Rates') return <Panel title="Contract rates" icon={<FileText size={17}/>}><div className="space-y-2">{laneContracts.length?laneContracts.map(x=><div key={x.contract_id} className="flex items-center justify-between rounded-xl border border-[#edf0f5] p-4"><div><div className="text-xs font-extrabold">{x.contract_id}</div><div className="mt-1 text-[10px] text-[#8994a3]">{x.carrier}</div></div><div className="text-right"><div className="text-sm font-black">₹{fmt(Number(x.contract_rate||0))}</div><div className="text-[9px] text-[#8994a3]">contract rate</div></div></div>):<Empty text="No contract rates are linked to this lane."/>}</div></Panel>
  if(tab==='Contracts') return <Panel title="Linked contracts" icon={<FileText size={17}/>}><div className="space-y-2">{laneContracts.length?laneContracts.map(x=><div key={x.contract_id} className="rounded-xl border border-[#edf0f5] p-4"><div className="flex items-center justify-between"><span className="text-xs font-extrabold">{x.contract_id}</span><span className="text-[10px] font-black">{fmt(Number(x.contracted_volume||0))} units</span></div><div className="mt-2 flex flex-wrap gap-3 text-[10px] text-[#8994a3]"><span>{x.carrier}</span><span>{x.start_date} → {x.end_date}</span></div></div>):<Empty text="No contracts are linked to this lane."/>}</div></Panel>
  return <Panel title="Linked shipments" icon={<Truck size={17}/>}><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-xs"><thead className="text-[9px] uppercase tracking-wide text-[#8994a3]"><tr><th className="px-3 py-2">Shipment</th><th className="px-3 py-2">Carrier</th><th className="px-3 py-2">Date</th><th className="px-3 py-2">Volume</th><th className="px-3 py-2">Status</th></tr></thead><tbody>{laneShipments.map(s=><tr key={s.shipment_id} className="border-t border-[#edf0f5]"><td className="px-3 py-3 font-extrabold">{s.shipment_id}</td><td className="px-3 py-3">{s.carrier||'—'}</td><td className="px-3 py-3 text-[#657386]">{s.shipment_date||'—'}</td><td className="px-3 py-3 font-bold">{fmt(Number(s.volume||0))}</td><td className="px-3 py-3"><span className="rounded-md bg-[#f6f8fb] px-2 py-1 text-[9px] font-black">{s.status||'—'}</span></td></tr>)}</tbody></table></div>{!laneShipments.length&&<Empty text="No shipments are linked to this lane."/>}</Panel>
 }
 return <main className="min-h-[calc(100vh-64px)] bg-[#f6f8fb] px-3 py-4 text-[#08111f] sm:px-6 sm:py-7 lg:px-8"><div className="mx-auto max-w-[1480px]"><button onClick={onBack} className="mb-4 inline-flex items-center gap-2 rounded-lg px-2 py-2 text-[10px] font-extrabold text-[#1769e0] hover:bg-white"><ArrowLeft size={14}/>Back to lane intelligence</button><section className="rounded-3xl border border-[#dbe2ec] bg-white p-4 sm:p-7"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div className="min-w-0"><div className="text-[9px] font-black uppercase tracking-[.18em] text-[#1769e0]">Lane 360</div><h1 className="mt-2 break-words text-2xl font-black tracking-[-.04em] sm:text-4xl">{lane.origin} → {lane.destination}</h1><p className="mt-2 text-xs text-[#8994a3]">{lane.mode||'Mode not recorded'} · {lane.carrier||'Carrier not assigned'}{lane.distance_km?` · ${fmt(Number(lane.distance_km))} km`:''}</p></div><div className="flex flex-wrap gap-2"><button onClick={onSim} className="rounded-xl border border-[#dbe2ec] px-4 py-2.5 text-[10px] font-extrabold">Run simulation</button><button onClick={()=>setTab('Overview')} className="rounded-xl bg-[#1769e0] px-4 py-2.5 text-[10px] font-extrabold text-white">Review recommendation</button></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Kpi label="Ghost risk" value={pct(risk)}/><Kpi label="Contracted" value={fmt(c)}/><Kpi label="Realized" value={fmt(m)}/><Kpi label="Ghost exposure" value={fmt(ghost)}/></div><div className="mt-6 overflow-hidden rounded-2xl border border-[#dbe2ec]"><div className="flex gap-1 overflow-x-auto p-2">{tabs.map(x=><button key={x} onClick={()=>setTab(x)} className={`shrink-0 rounded-lg px-3 py-2.5 text-[10px] font-extrabold transition ${tab===x?'bg-[#edf4ff] text-[#1769e0]':'text-[#657386] hover:bg-[#f6f8fb]'}`}>{x}</button>)}</div></div><div className="mt-5">{content()}</div></section></div></main>
}
function Kpi({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-[#dbe2ec] bg-white p-4"><div className="text-[9px] font-black uppercase tracking-wide text-[#8490a0]">{label}</div><div className="mt-2 text-2xl font-black tracking-[-.04em]">{value}</div></div>}
function Panel({title,icon,children}:{title:string;icon?:React.ReactNode;children:React.ReactNode}){return <section className="rounded-2xl border border-[#dbe2ec] bg-white p-5"><div className="flex items-center gap-2 text-sm font-extrabold">{icon&&<span className="text-[#1769e0]">{icon}</span>}{title}</div><div className="mt-4">{children}</div></section>}
function Metric({label,value}:{label:string;value:string}){return <div className="flex items-center justify-between border-b border-[#edf0f5] py-3 text-xs"><span className="text-[#8994a3]">{label}</span><strong>{value}</strong></div>}
function Signal({label,value}:{label:string;value:string}){return <div className="flex items-center justify-between py-2 text-xs"><span className="text-[#8994a3]">{label}</span><strong>{value}</strong></div>}
function Driver({title,value,detail}:{title:string;value:string;detail:string}){return <div className="flex items-center justify-between rounded-xl bg-[#f6f8fb] p-3"><div><div className="text-xs font-extrabold">{title}</div><div className="mt-1 text-[9px] text-[#8994a3]">{detail}</div></div><div className="text-sm font-black">{value}</div></div>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed border-[#dbe2ec] p-7 text-center text-[11px] font-bold text-[#8994a3]">{text}</div>}
