'use client'

import { useEffect, useMemo, useRef } from 'react'
import { ExternalLink, MapPin, Navigation, Radio, Siren, Truck } from 'lucide-react'

type Shipment={shipment_id:string;lane_id:string;carrier:string;status:string;live_lat:number|null;live_lng:number|null;current_eta:string|null;vehicle_id:string|null;risk_score:number|null}
type Lane={id:string;origin:string;destination:string}
type Help={shipment_id:string;status:string;latitude:number|null;longitude:number|null}

const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n))
const riskClass=(risk:number)=>risk>=70?'bg-[#fff0f0] text-[#b54747]':risk>=45?'bg-[#fff8e7] text-[#9b6a00]':'bg-[#eef9f4] text-[#23825b]'

export function LiveOperationsMap({shipments,lanes,help,selectedId,onSelect}:{shipments:Shipment[];lanes:Lane[];help:Help[];selectedId:string;onSelect:(id:string)=>void}){
 const points=shipments.filter(s=>s.live_lat!=null&&s.live_lng!=null)
 const selected=shipments.find(s=>s.shipment_id===selectedId)
 const selectedPoint=selected?.live_lat!=null&&selected?.live_lng!=null?selected:null
 const center=useMemo(()=>{const p=selectedPoint||points[0];return p?{lat:Number(p.live_lat),lng:Number(p.live_lng)}:{lat:20.5937,lng:78.9629}},[selectedPoint,points])
 const mapRef=useRef<HTMLDivElement>(null)
 useEffect(()=>{if(!mapRef.current||!points.length)return;const markers=points.map(p=>{const risk=Number(p.risk_score||0);return `<button title="${p.shipment_id.replace(/"/g,'&quot;')}" data-shipment="${p.shipment_id.replace(/"/g,'&quot;')}" style="left:${50+clamp((Number(p.live_lng)-center.lng)*1.5,-43,43)}%;top:${50-clamp((Number(p.live_lat)-center.lat)*1.5,-40,40)}%" class="gl-map-marker ${risk>=70?'high':risk>=45?'medium':'low'}">${p.vehicle_id?'🚚':'•'}</button>`}).join('');mapRef.current.innerHTML=markers;const handlers=Array.from(mapRef.current.querySelectorAll('[data-shipment]')).map(el=>{const fn=()=>onSelect(el.getAttribute('data-shipment')||'');el.addEventListener('click',fn);return [el,fn] as const});return()=>handlers.forEach(([el,fn])=>el.removeEventListener('click',fn))},[points,center,onSelect])
 const lane=selected?lanes.find(l=>l.id===selected.lane_id):undefined
 const directions=lane?`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(lane.origin)}&destination=${encodeURIComponent(lane.destination)}`:''
 return <section className="overflow-hidden rounded-3xl border border-[#dbe2ec] bg-white"><div className="flex flex-col gap-3 border-b border-[#edf0f5] p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.15em] text-[#1769e0]"><Radio size={13}/> Live map</div><h2 className="mt-2 text-lg font-black">Fleet position</h2><p className="mt-1 text-[10px] text-[#8994a3]">Only connected shipment coordinates are shown. No location is invented.</p></div>{lane&&<a href={directions} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-[#dbe2ec] px-3 py-2 text-[10px] font-black"><Navigation size={12}/>Directions<ExternalLink size={11}/></a>}</div><div className="relative h-[360px] overflow-hidden bg-[#edf2f7]"><div className="absolute inset-0 opacity-60" style={{backgroundImage:'linear-gradient(#d6dee8 1px,transparent 1px),linear-gradient(90deg,#d6dee8 1px,transparent 1px)',backgroundSize:'48px 48px'}}/><div className="absolute left-1/2 top-1/2 h-64 w-64 -translate-x-1/2 -translate-y-1/2 rounded-full border border-[#cbd5e1]"/><div className="absolute left-1/2 top-1/2 h-40 w-40 -translate-x-1/2 -translate-y-1/2 rounded-full border border-[#d5dde7]"/><div ref={mapRef} className="absolute inset-0"/><div className="absolute bottom-4 left-4 rounded-2xl border border-[#dbe2ec] bg-white/95 p-3 text-[9px] font-bold shadow-sm"><div className="font-black">{points.length} positioned shipment{points.length===1?'':'s'}</div><div className="mt-1 text-[#8994a3]">Center: {center.lat.toFixed(3)}, {center.lng.toFixed(3)}</div></div>{!points.length&&<div className="absolute inset-0 flex items-center justify-center p-6 text-center"><div className="rounded-2xl border border-dashed border-[#cfd8e3] bg-white/95 p-7"><MapPin className="mx-auto text-[#1769e0]" size={25}/><div className="mt-3 text-sm font-black">No live coordinates yet</div><p className="mt-1 max-w-sm text-[10px] leading-5 text-[#8994a3]">Connect your TMS, telematics or driver location feed to populate this map.</p></div></div>}</div><div className="grid gap-2 border-t border-[#edf0f5] p-3 sm:grid-cols-3">{shipments.slice(0,6).map(s=>{const h=help.find(x=>x.shipment_id===s.shipment_id&&x.status==='open');return <button key={s.shipment_id} onClick={()=>onSelect(s.shipment_id)} className={`rounded-xl p-3 text-left ${s.shipment_id===selectedId?'bg-[#edf4ff]':'bg-[#f7f9fc]'}`}><div className="flex items-center justify-between gap-2"><span className="flex items-center gap-1 text-[10px] font-black"><Truck size={12}/>{s.vehicle_id||s.shipment_id}</span><span className={`rounded-md px-1.5 py-1 text-[8px] font-black ${riskClass(Number(s.risk_score||0))}`}>{Math.round(Number(s.risk_score||0))}%</span></div>{h&&<div className="mt-2 flex items-center gap-1 text-[9px] font-black text-[#b54747]"><Siren size={10}/>Help open</div>}</button>})}</div></section>
}
