'use client'
import { useEffect, useMemo, useState } from 'react'
import dynamic from 'next/dynamic'
import { AlertTriangle, Clock3, MapPin, Navigation, Radio, RefreshCw, Route, Siren, Truck } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'

const LiveOperationsMap = dynamic(
  () => import('@/components/live-operations-map').then(m => m.LiveOperationsMap),
  {
    ssr: false,
    loading: () => (
      <div className="flex h-[420px] w-full flex-col items-center justify-center rounded-3xl border border-[#dbe2ec] bg-white p-6 text-center animate-pulse">
        <div className="mb-3 flex h-10 w-10 items-center justify-center rounded-2xl bg-[#edf4ff] text-[#1769e0]">
          <MapPin size={20} className="animate-bounce" />
        </div>
        <div className="mb-2 h-4 w-48 rounded bg-[#edf0f5]" />
        <div className="h-3 w-64 rounded bg-[#f3f5f9]" />
      </div>
    )
  }
)

type Shipment={shipment_id:string;lane_id:string;carrier:string;shipment_date:string;volume:number;status:string;live_lat:number|null;live_lng:number|null;current_eta:string|null;current_route:string|null;last_event_at:string|null;help_status:string|null;vehicle_capacity:number|null;vehicle_id:string|null;risk_score:number|null}
type Lane={id:string;origin:string;destination:string;mode:string;distance_km:number|null;risk_score:number|null}
type Event={id:string;shipment_id:string;event_type:string;severity:string;message:string|null;created_at:string}
type Help={id:string;shipment_id:string;status:string;reason:string|null;latitude:number|null;longitude:number|null;relief_shipment_id:string|null;created_at:string}
const pct=(v:number|null)=>`${Math.round(Math.max(0,Math.min(100,Number(v||0))))}%`
const clock=(v:string|null)=>v?new Date(v).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'}):'—'
export function LiveOperations({shipments:initialShipments,lanes,events:initialEvents,help:initialHelp}:{shipments:Shipment[];lanes:Lane[];events:Event[];help:Help[]}){
 const db=createClient();const [shipments,setShipments]=useState(initialShipments);const [events,setEvents]=useState(initialEvents);const [help,setHelp]=useState(initialHelp);const [selectedId,setSelectedId]=useState(initialShipments[0]?.shipment_id||'');const [busy,setBusy]=useState('');const [notice,setNotice]=useState('')
 const selected=shipments.find(s=>s.shipment_id===selectedId)||shipments[0];const lane=lanes.find(l=>l.id===selected?.lane_id);const openHelp=help.find(h=>h.shipment_id===selected?.shipment_id&&h.status==='open');const selectedEvents=useMemo(()=>events.filter(e=>e.shipment_id===selected?.shipment_id).slice(0,10),[events,selected?.shipment_id])
 const active=shipments.filter(s=>!['delivered','completed','cancelled'].includes((s.status||'').toLowerCase())).length;const high=shipments.filter(s=>Number(s.risk_score||0)>=70).length;const overdue=shipments.filter(s=>s.current_eta&&new Date(s.current_eta)<new Date()&&!['delivered','completed'].includes((s.status||'').toLowerCase())).length
 useEffect(()=>{const c=db.channel('ghostlane-ops').on('postgres_changes',{event:'*',schema:'public',table:'shipments'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'shipment_events'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'shipment_help_requests'},refresh).subscribe();return()=>{db.removeChannel(c)}},[])
 async function refresh(){const [{data:s},{data:e},{data:h}]=await Promise.all([db.from('shipments').select('*').order('shipment_date',{ascending:false}).limit(500),db.from('shipment_events').select('*').order('created_at',{ascending:false}).limit(500),db.from('shipment_help_requests').select('*').order('created_at',{ascending:false}).limit(200)]);if(s)setShipments(s as Shipment[]);if(e)setEvents(e as Event[]);if(h)setHelp(h as Help[])}
 async function event(type:string,message:string,severity='info'){if(!selected)return;setBusy(type);const now=new Date().toISOString();const {error}=await db.from('shipment_events').insert({shipment_id:selected.shipment_id,event_type:type,severity,message,latitude:selected.live_lat,longitude:selected.live_lng,eta_before:selected.current_eta,eta_after:selected.current_eta});if(!error){await db.from('shipments').update({last_event_at:now}).eq('shipment_id',selected.shipment_id);await refresh();setNotice('Event recorded')}else setNotice(error.message);setBusy('');setTimeout(()=>setNotice(''),2500)}
 async function reoptimize(){if(!selected||!lane)return;setBusy('route');const route=`${lane.origin} → ${lane.destination} · recalculated ${clock(new Date().toISOString())}`;const {error}=await db.from('shipments').update({current_route:route,last_event_at:new Date().toISOString()}).eq('shipment_id',selected.shipment_id);if(!error){await db.from('shipment_events').insert({shipment_id:selected.shipment_id,event_type:'route_reoptimized',severity:'warning',message:'Feasible route recalculated from latest operational signal',latitude:selected.live_lat,longitude:selected.live_lng});await refresh();setNotice('Route re-optimized')}else setNotice(error.message);setBusy('');setTimeout(()=>setNotice(''),2500)}
 async function helpRequest(){if(!selected)return;setBusy('help');const {error}=await db.from('shipment_help_requests').insert({shipment_id:selected.shipment_id,status:'open',reason:'Driver unable to continue',latitude:selected.live_lat,longitude:selected.live_lng});if(!error){await db.from('shipments').update({help_status:'open',last_event_at:new Date().toISOString()}).eq('shipment_id',selected.shipment_id);await db.from('shipment_events').insert({shipment_id:selected.shipment_id,event_type:'help_signal',severity:'critical',message:'Driver requested assistance',latitude:selected.live_lat,longitude:selected.live_lng});await refresh();setNotice('Help workflow opened')}else setNotice(error.message);setBusy('');setTimeout(()=>setNotice(''),2500)}
 async function resolveHelp(){if(!selected||!openHelp)return;setBusy('resolve');const reliefId=`RELIEF-${selected.shipment_id.replace(/^SHP-?/,'')}`;const now=new Date().toISOString();const {error:hErr}=await db.from('shipment_help_requests').update({status:'resolved',relief_shipment_id:reliefId}).eq('id',openHelp.id);if(!hErr){await db.from('shipments').update({help_status:'resolved',last_event_at:now}).eq('shipment_id',selected.shipment_id);await db.from('shipment_events').insert({shipment_id:selected.shipment_id,event_type:'relief_dispatched',severity:'info',message:`Relief unit ${reliefId} assigned and dispatched. Help request marked resolved.`,latitude:selected.live_lat,longitude:selected.live_lng});await refresh();setNotice(`Relief unit ${reliefId} dispatched and request resolved`)}else setNotice(hErr.message);setBusy('');setTimeout(()=>setNotice(''),2800)}
 if(!shipments.length)return <Empty/>;if(!selected||!lane)return <Empty/>
 return <main className="min-h-[calc(100vh-64px)] bg-[#f6f8fb] px-4 py-7 text-[#08111f] sm:px-6 lg:px-8"><div className="mx-auto max-w-[1480px]">
 <header className="flex flex-col gap-4 border-b border-[#dbe2ec] pb-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-[9px] font-black uppercase tracking-[.18em] text-[#1769e0]">Live operations</div><h1 className="mt-2 text-3xl font-black tracking-[-.05em]">Predict before you contract. Optimize while you move.</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#66758a]">Live shipment monitoring, event detection, route re-optimization and driver assistance from connected operational records.</p></div><button onClick={refresh} className="inline-flex items-center gap-2 rounded-xl border border-[#dbe2ec] bg-white px-4 py-2.5 text-[11px] font-black"><RefreshCw size={14}/>Refresh</button></header>
 <section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Active trucks" value={String(active)}/><Kpi label="High ghost risk" value={String(high)}/><Kpi label="ETA overdue" value={String(overdue)}/><Kpi label="Open help" value={String(help.filter(h=>h.status==='open').length)}/></section>
 <div className="mt-5"><LiveOperationsMap shipments={shipments} lanes={lanes} help={help} selectedId={selected.shipment_id} onSelect={setSelectedId}/></div>
 <div className="mt-5 grid gap-5 xl:grid-cols-[.4fr_1fr]"><section className="overflow-hidden rounded-3xl border border-[#dbe2ec] bg-white"><div className="border-b border-[#edf0f5] p-5"><div className="text-[9px] font-black uppercase tracking-[.15em] text-[#8490a0]">Truck moving</div><h2 className="mt-2 text-sm font-extrabold">Select shipment</h2></div><div className="max-h-[620px] overflow-y-auto p-2">{shipments.map(s=><button key={s.shipment_id} onClick={()=>setSelectedId(s.shipment_id)} className={`w-full rounded-2xl p-4 text-left ${s.shipment_id===selected.shipment_id?'bg-[#edf4ff]':'hover:bg-[#f7f9fc]'}`}><div className="flex items-center justify-between gap-2"><span className="text-xs font-black">{s.shipment_id}</span><span className="rounded-md bg-[#f7f9fc] px-2 py-1 text-[9px] font-black">{pct(s.risk_score)} risk</span></div><div className="mt-2 text-[10px] text-[#718096]">{s.carrier||'Carrier not assigned'} · {s.status||'Recorded'}</div><div className="mt-2 flex gap-2 text-[9px] text-[#8994a3]"><Truck size={12}/>{s.vehicle_id||'Vehicle unavailable'} · <Clock3 size={12}/>{clock(s.current_eta)}</div></button>)}</div></section>
 <section className="space-y-5"><div className="rounded-3xl border border-[#dbe2ec] bg-white p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.15em] text-[#8490a0]"><MapPin size={14}/> Live shipment</div><h2 className="mt-3 text-2xl font-black">{lane.origin} → {lane.destination}</h2><p className="mt-1 text-xs text-[#8994a3]">{selected.shipment_id} · {selected.carrier||'Carrier not assigned'} · {selected.vehicle_id||'vehicle unavailable'}</p></div><span className="inline-flex items-center gap-2 rounded-full bg-[#f5fbf7] px-3 py-1.5 text-[9px] font-black text-[#39765a]"><span className="h-1.5 w-1.5 rounded-full bg-[#22a06b]"/>Connected</span></div>
 <div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Ghost risk" value={pct(selected.risk_score)}/><Metric label="Current ETA" value={clock(selected.current_eta)}/><Metric label="Live location" value={selected.live_lat!=null&&selected.live_lng!=null?`${selected.live_lat.toFixed(3)}, ${selected.live_lng.toFixed(3)}`:'Unavailable'}/><Metric label="Vehicle capacity" value={selected.vehicle_capacity?`${selected.vehicle_capacity} units`:'Unavailable'}/></div>
 <div className="mt-5 rounded-2xl bg-[#08111f] p-5 text-white"><div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.15em] text-[#83b4ff]"><Route size={14}/> Optimal route</div><div className="mt-3 text-sm font-black">{selected.current_route||`${lane.origin} → ${lane.destination}`}</div><p className="mt-2 text-[10px] leading-5 text-[#aab5c3]">Route scoring is designed to consume traffic, road conditions, capacity, priority, time windows, distance, travel time and fuel when those signals are connected.</p><button disabled={busy==='route'} onClick={reoptimize} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-[10px] font-black text-[#08111f]"><Navigation size={13}/>{busy==='route'?'Re-optimizing…':'Re-optimize route'}</button></div>
 <div className="mt-5 flex flex-wrap gap-2"><Action label="Traffic increase" busy={busy==='traffic'} onClick={()=>event('traffic_increase','Traffic increase detected','warning')}/><Action label="Road incident" busy={busy==='road'} onClick={()=>event('road_incident','Road incident detected','warning')}/><Action label="Vehicle delay" busy={busy==='delay'} onClick={()=>event('vehicle_delay','Vehicle delay detected','warning')}/><button disabled={busy==='help'||!!openHelp} onClick={helpRequest} className="inline-flex items-center gap-2 rounded-xl bg-[#fff0f0] px-3 py-2 text-[10px] font-black text-[#b54747] disabled:opacity-50"><Siren size={13}/>{openHelp?'Help open':'Driver needs help'}</button></div></div>
 <div className="grid gap-5 lg:grid-cols-[1fr_.72fr]"><section className="rounded-3xl border border-[#dbe2ec] bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="text-sm font-extrabold">Live event stream</h2><p className="mt-1 text-[10px] text-[#8994a3]">Signals that trigger warnings and re-optimization.</p></div><Radio size={16} className="text-[#1769e0]"/></div><div className="mt-5 space-y-3">{selectedEvents.length?selectedEvents.map(e=><div key={e.id} className="rounded-xl bg-[#f7f9fc] p-3"><div className="flex justify-between gap-3"><span className="text-[10px] font-black capitalize">{e.event_type.replaceAll('_',' ')}</span><span className="text-[9px] text-[#8994a3]">{clock(e.created_at)}</span></div><p className="mt-1 text-[10px] text-[#718096]">{e.message||'Operational event recorded.'}</p></div>):<EmptyBlock text="No events recorded yet."/>}</div></section><section className="rounded-3xl border border-[#dbe2ec] bg-white p-6"><div className="text-[9px] font-black uppercase tracking-[.15em] text-[#8490a0]">Driver help</div><h2 className="mt-4 text-lg font-black">{openHelp?'Relief action required':'Ready for support'}</h2><p className="mt-2 text-xs leading-5 text-[#66758a]">{openHelp?'The request contains the latest available location and shipment context. Match a suitable relief truck from connected fleet availability.':'If the driver cannot continue, open a help signal. GhostLane records the request without fabricating a relief assignment.'}</p>{openHelp&&<div className="mt-5 space-y-3"><div className="rounded-2xl bg-[#fff8e7] p-4 text-[10px] font-bold text-[#765900]">Help request open since {clock(openHelp.created_at)}: {openHelp.reason||'Assistance requested'}.</div><button disabled={busy==='resolve'} onClick={resolveHelp} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#22a06b] px-4 py-2.5 text-[11px] font-black text-white transition hover:bg-[#1a8256] disabled:opacity-50">{busy==='resolve'?'Dispatching relief…':'Dispatch Relief & Resolve Request'}</button></div>}</section></div></section></div>
 {notice&&<div className="fixed bottom-5 right-5 z-50 rounded-xl bg-[#08111f] px-4 py-3 text-[10px] font-black text-white shadow-2xl">{notice}</div>}</div></main>
}
function Kpi({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-[#dbe2ec] bg-white p-5"><div className="text-[9px] font-black uppercase tracking-[.12em] text-[#8490a0]">{label}</div><div className="mt-3 text-3xl font-black">{value}</div></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-[#f7f9fc] p-4"><div className="text-[9px] font-black uppercase tracking-[.1em] text-[#8490a0]">{label}</div><div className="mt-2 text-lg font-black">{value}</div></div>}
function Action({label,onClick,busy}:{label:string;onClick:()=>void;busy:boolean}){return <button onClick={onClick} disabled={busy} className="inline-flex items-center gap-2 rounded-xl border border-[#dbe2ec] bg-white px-3 py-2 text-[10px] font-black disabled:opacity-50"><AlertTriangle size={12}/>{busy?'Recording…':label}</button>}
function EmptyBlock({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-[#dbe2ec] p-8 text-center text-[10px] font-semibold text-[#8994a3]">{text}</div>}
function Empty(){return <main className="min-h-[calc(100vh-64px)] bg-[#f6f8fb] px-5 py-10"><div className="mx-auto max-w-xl rounded-3xl border border-[#dbe2ec] bg-white p-10 text-center"><Truck className="mx-auto text-[#1769e0]" size={32}/><h1 className="mt-4 text-xl font-black">Live operations needs shipment data</h1><p className="mt-2 text-xs leading-5 text-[#66758a]">Import real shipment and lane records first. GhostLane will not create fake trucks, locations or routes.</p></div></main>}
